export {default as Logo} from './zamon.svg'
export {default as India} from './europe.jpg'
export {default as dubai} from './dubai.jpg'
export {default as istanbul} from './istanbul.jpg'
export {default as sauida} from './saudia.jpg'
export {default as sharm} from './sharm.jpg'
export {default as offer} from './offers.jpg'
export {default as usa} from './usa.jpg'
export {default as canada} from './canada.jpg'
export {default as deals} from './deals.jpg'
export {default as eng} from  './eng.jpg'
export {default as oman} from './oman.jpg'
export {default as train} from './poyezd.jpg'
export {default as airplane} from './samalyotjon.jpg'
export {default as antalia } from './antailya.jpg'
export {default as bg} from './bg.jpg'
export {default as hamburger} from './hamburger2.png'